<?php

function pont_menu()
{
  $items = array();
  $items['pont/list'] = array(
    'title' => 'Vasarlok',
    'page callback' => 'pont_ponts',
    'access callback' => true,
    'type' => MENU_NORMAL_ITEM,
  );
  $items['vasarlo/edit'] = array(
    'title' => t('Vasarlo hozzadasa'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('pont_pont_form'),
    'access callback' => true,
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

function pont_ponts()
{
  $query = db_select('pont', 'b');
  $result = $query->fields('b',array('nev','cim','telefonszam','pontok','email','azonosito'))->execute();
  $header = array('Név', 'Cím', 'Telefonszám','Pontok', 'E-mail', 'Azonosító');
  $rows=array();
  foreach ($result as $record) {
	dpm($record);
  $rows[]=array($record->id,
          $record->nev,
          $record->cim,
          $record->telefonszam,
          $record->pontok,
          $record->email,
          $record->azonosito,
         
  }
  
  $render_array=array();
  $render_array['ponttable'] = array(
    '#theme' => 'table',
    '#header' => $header,
    '#rows' => $rows,
  );

  return $render_array;
}




function pont_pont_form($form,$form_state,$id=0){
  
  if ($id>0) {
    $query = db_select('vasarlo', 'b');	
    $result = $query
	           ->condition('b.azonosito', $id, '=')
	           ->fields('b',array('nev','cim','telefonszam','pontok','email','azonosito',))
			   ->execute();
    foreach ($result as $record) {$vasarlo=$record;}
	$nev = $vasarlo->nev;
	$cim = $vasarlo->cim;
	$telefonszam = $vasarlo->telefonszam;
  $pontok = $vasarlo->pontok;
  $email = $vasarlo->email;
  $azonosito = $vasarlo->azonosito;
  
  }
  else {
    $nev = '';
    $cim = '';
    $telefonszam = '';
    $pontok= '';
    $email= '';
    $azonosito= '';
    
  }
  
  function pont_update($form,&$form_state){
  dpm($form_state);
  db_update('vasarlo')
	  ->fields(array(
	   
    'pontok' => $pontok
    'azonosito' => $azonosito,
   ))
	  ->condition('azonosito', $azonosito, '=')
	  ->execute();
	drupal_set_message('Pontok modositva');

  $pontok = $form_state['values']['pontok'];
 
 /*fieldset*/
  $form = array();
    $form['fieldset1'] = array(
    '#type' => 'fieldset',
    '#title' => 'A vásárló adatai',
  );
    $form['fieldset1']['nev'] = array(
    '#type' => 'textfield',
    '#required' => TRUE,
    '#title' => t('Név'),
  '#default_value' => $nev , 
  );

  $form['fieldset1']['cim'] = array(
    '#type' => 'textfield',
    '#required' => TRUE,
    '#title' => t('Cím'),
  '#default_value' => $cim , 
  );
  
  
  $form['fieldset1']['telefonszam'] = array(
    '#type' => 'textfield',
    '#required' => TRUE,
    '#title' => t('Telefonszám'),
  '#default_value' => $telefonszam , 
  );
  
  
  $form['fieldset1']['pontok'] = array(
    '#type' => 'textfield',
    '#required' => False,
    '#title' => t('Pontok száma'),
  '#default_value' => 0 , 
  );
  
    $form['fieldset1']['email'] = array(
    '#type' => 'textfield',
    '#required' => True,
    '#title' => t('E-mail cím'),
  '#default_value' => $email , 
  );
  
     $form['fieldset1']['email'] = array(
    '#type' => 'textfield',
    '#required' => True,
    '#title' => t('E-mail cím'),
  '#default_value' => $email , 
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Rögzítés'),
  );
  return $form;  
}
function pontok_pont_form_validate($form,&$form_state){
  if(!valid_email_address($form_state['values']['email'])){
   form_set_error('email','Hibas email cím, adj meg másikat.');
  }
}
function pont_pont_form_submit($form,&$form_state){
  dpm($form_state);
  $nev = $form_state['values']['nev'];
  $cim = $form_state['values']['cim'];
  $telefonszam = $form_state['values']['telefonszam'];
  $pontok = $form_state['values']['pontok'];
  $email = $form_state['values']['email'];
  $azonosito = $form_state['values']['azonosito'];
  
  if ($id==0) {
    db_insert('vasarlo')
      ->fields(array(
	'nev' => $nev,
	'cim' => $cim,		'ar' => $ar,
    'telefonszam' => $telefonszam,
    'pontok' => $pontok,
    'email' => $email,
    'azonosito' => $azonosito,
	   ))
	   ->execute();
  drupal_set_message('A' .$nev.' - '.$azonosito.' vásárló bekerült az adatbázisunkba');
  }
  else {
    db_update('vasarlo')
	  ->fields(array(
	    'nev' => $nev,
		'cim' => $cim,
		'telefonszam' => $telefonszam,
    'pontok' => $pontok,
    'email' => $email,
    'azonosito' => $azonosito,
  
	   ))
	  ->condition('azonosito', $azonosito, '=')
	  ->execute();
	drupal_set_message('Valtoztatasok ervenybe leptek');
  }
}